export enum CodeMessage {
    FORBIDDEN = 'FORBIDDEN', // Permission denied
    UNAUTHORIZED = 'UNAUTHORIZED',

    //user
    USER_NOT_EXIST = 'USER_NOT_EXIST',
    USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
    PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
    USER_IS_DELETED = 'USER_IS_DELETED',
    ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_ADMIN = 'ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_ADMIN',
    ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_MANAGER = 'ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_MANAGER',
    ROLE_MANAGER_NOT_CREATE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_NOT_CREATE_FOR_ROLE_ADMIN',

    ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_MANAGER = 'ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_MANAGER',
    ROLE_MANAGER_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_USER_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_USER_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_USER_NOT_UPDATE_FOR_ROLE_MANAGER = 'ROLE_USER_NOT_UPDATE_FOR_ROLE_MANAGER',
    ROLE_USER_NOT_UPDATE_FOR_ROLE_DOCTOR = 'ROLE_USER_NOT_UPDATE_FOR_ROLE_DOCTOR',

    ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_USER = 'ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_USER',


    ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_ADMIN',
    ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_USER = 'ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_USER',

    //CLINIC
    CLINIC_ALREADY_EXIST = 'CLINIC_ALREADY_EXIST',
    CLINIC_NOT_EXIST = 'CLINIC_NOT_EXIST',

    //CLINIC_INFORMATION
    CLINIC_INFOR_NOT_EXIST = 'CLINIC_INFOR_NOT_EXIST',
    CLINIC_NOT_MATCH = 'CLINIC_NOT_MATCH',

    // DOCTOR
    DOCTOR_NOT_EXIST = 'DOCTOR_NOT_EXIST',

    //DOCTOR_INFOR
    DOCTOR_INFOR_NOT_EXIST = 'DOCTOR_INFOR_NOT_EXIST',

    // SPECIALTY
    SPECIALTY_AREADY_EXIST = 'SPECIALTY_AREADY_EXIST',
    SPECIALTY_NOT_EXIST = 'SPECIALTY_NOT_EXIST',
    PARSE_SPECIALTY_IDS_ERROR = 'PARSE_SPECIALTY_IDS_ERROR',

    // Save Images
    ONLY_IMAGE_FILES_ARE_ALLOWED = 'ONLY_IMAGE_FILES_ARE_ALLOWED',
}