export enum CodeMessage {
    FORBIDDEN = 'FORBIDDEN', // Permission denied
    UNAUTHORIZED = 'UNAUTHORIZED',

    //user
    USER_NOT_EXIST = 'USER_NOT_EXIST',
    USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
    PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
    NEW_PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH = 'NEW_PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH',
    CURRENT_PASSWORD_INVALID = 'CURRENT_PASSWORD_INVALID',

    USER_IS_DELETED = 'USER_IS_DELETED',
    ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_ADMIN = 'ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_ADMIN',
    ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_MANAGER = 'ROLE_DOCTOR_NOT_CREATE_FOR_ROLE_MANAGER',
    ROLE_MANAGER_NOT_CREATE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_NOT_CREATE_FOR_ROLE_ADMIN',

    ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_MANAGER = 'ROLE_DOCTOR_NOT_UPDATE_FOR_ROLE_MANAGER',
    ROLE_MANAGER_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_USER_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_USER_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_USER_NOT_UPDATE_FOR_ROLE_MANAGER = 'ROLE_USER_NOT_UPDATE_FOR_ROLE_MANAGER',
    ROLE_USER_NOT_UPDATE_FOR_ROLE_DOCTOR = 'ROLE_USER_NOT_UPDATE_FOR_ROLE_DOCTOR',

    ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_ADMIN',
    ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_USER = 'ROLE_MANAGER_CLINIC_NOT_UPDATE_FOR_ROLE_USER',


    ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_ADMIN = 'ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_ADMIN',
    ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_USER = 'ROLE_MANAGER_CLINIC_NOT_DELETE_FOR_ROLE_USER',

    //CLINIC
    CLINIC_ALREADY_EXIST = 'CLINIC_ALREADY_EXIST',
    CLINIC_NOT_EXIST = 'CLINIC_NOT_EXIST',

    //CLINIC_INFORMATION
    CLINIC_INFOR_NOT_EXIST = 'CLINIC_INFOR_NOT_EXIST',
    CLINIC_NOT_MATCH = 'CLINIC_NOT_MATCH',

    // DOCTOR
    DOCTOR_NOT_EXIST = 'DOCTOR_NOT_EXIST',
    DOCTOR_NOT_MATCH = 'DOCTOR_NOT_MATCH',

    //DOCTOR_INFOR
    DOCTOR_INFOR_NOT_EXIST = 'DOCTOR_INFOR_NOT_EXIST',

    // SPECIALTY
    SPECIALTY_AREADY_EXIST = 'SPECIALTY_AREADY_EXIST',
    SPECIALTY_NOT_EXIST = 'SPECIALTY_NOT_EXIST',
    PARSE_SPECIALTY_IDS_ERROR = 'PARSE_SPECIALTY_IDS_ERROR',

    // Save Images
    ONLY_IMAGE_FILES_ARE_ALLOWED = 'ONLY_IMAGE_FILES_ARE_ALLOWED',

    // Send mail
    CAN_NOT_SEND_MAIL_TO_USER = 'CAN_NOT_SEND_MAIL_TO_USER',

    // Schedule
    TIMES_NOT_EMTY = 'TIMES_NOT_EMTY',
    TIME_END_MUST_BE_GREATER_THAN_TIME_START = 'TIME_END_MUST_BE_GREATER_THAN_TIME_START',
    START_DATE_MUST_BE_EQUAL_END_DATE = 'START_DATE_MUST_BE_EQUAL_END_DATE',
    TIME_START_OR_TIME_END_MUST_BE_GREATER_THAN_DATE_TIME_NOW = 'TIME_START_OR_TIME_END_MUST_BE_GREATER_THAN_DATE_TIME_NOW',
    SCHEDULE_NOT_EXIST = 'SCHEDULE_NOT_EXIST',
    DATE_MUST_BE_EQUAL_START_DATE_OR_END_DATE = 'DATE_MUST_BE_EQUAL_START_DATE_OR_END_DATE',
    TIME_START_NOT_BE_EQUAL_TIME_END = 'TIME_START_NOT_BE_EQUAL_TIME_END',
    MAXIMUN_COUNT = 'MAXIMUN_COUNT',
    YOU_HAVE_BOOKED = 'YOU_HAVE_BOOKED',
    APPOINTMENT_HAS_BEEN_BOOKED = 'APPOINTMENT_HAS_BEEN_BOOKED',

    // File
    FILE_CAN_NOT_EMPTY = 'FILE_CAN_NOT_EMPTY',

    // booking
    BOOKING_NOT_EXIST = 'BOOKING_NOT_EXIST',
} 